[project]
name = "ml_api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.0",
    "pydantic-settings>=2.5.2",
    "pydantic>=2.9.2",
    "uvicorn>=0.31.0",
]
