# Dockerfile.worker
FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1-mesa-dev

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY ./app ./app
COPY .env .

CMD ["celery", "-A", "app.service.celery_app", "worker", "--loglevel=info"]