version: '3.8'

services:
  # Redis - WebSocket mesajları için
  redis:
    image: redis:alpine
    container_name: chat-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    command: redis-server --appendonly yes
    networks:
      - chat-network

 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chat-backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    restart: always
    networks:
      - chat-network
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

 
  frontend:
    image: python:3.10-slim
    container_name: chat-frontend
    ports:
      - "9000:9000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: python -m http.server 9000
    networks:
      - chat-network
    restart: always

networks:
  chat-network:
    driver: bridge

volumes:
  redis-data: