version: '3.8'
name: model-registry
services:

  registry:
    build:
      context: ..
      dockerfile: mlops/Dockerfile.registry
    container_name: registry
    ports:
      - "${REGISTRY_PORT}:8000"
    volumes:
      - ../registry:/usr/src/app/registry
    environment:
      - MONGODB_URL=mongodb://${MONGODB_ROOT_USERNAME}:${MONGODB_ROOT_PASSWORD}@registry_mongodb:27017/
      - MINIO_ENDPOINT=registry-minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MONGODB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    
    command: ["uvicorn", "registry.api:app", "--host", "0.0.0.0","--reload"]
    depends_on:
      - registry_mongodb
      - registry-minio
    networks:
      - registry_network
      - mlops_network

  registry_mongodb:
    image: mongo:6.0
    container_name: registry_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    ports:
      - "${REGISTRY_MONGODB_PORT}:27017"
    volumes:
      - registry_mongodb_data:/data/db
    networks:
      - registry_network

  registry-minio:
    image: minio/minio:latest
    container_name: registry-minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    ports:
      - "${REGISTRY_MINIO_PORT}:9001"
      - "9005:9000"
    volumes:
      - registry_minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - registry_network


volumes:
  registry_mongodb_data:
  registry_minio_data:

networks:
    registry_network:
      driver: bridge
    mlops_network:
      external: true